// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkLevbcna-YzBbhoiXWwkoOtpPUxjTpQ',
    appId: '1:304480919302:web:79c81577feee8443e98887',
    messagingSenderId: '304480919302',
    projectId: 'nutri-guard-48855',
    authDomain: 'nutri-guard-48855.firebaseapp.com',
    storageBucket: 'nutri-guard-48855.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zJXV4TI-g761rh7qcwAmV-8nbsYvwvw',
    appId: '1:304480919302:android:0820afca5786ece8e98887',
    messagingSenderId: '304480919302',
    projectId: 'nutri-guard-48855',
    storageBucket: 'nutri-guard-48855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT-wzD2r_KOZX_oDSlI3hjzWe2sexS85E',
    appId: '1:304480919302:ios:6ae0e1053b6dfc23e98887',
    messagingSenderId: '304480919302',
    projectId: 'nutri-guard-48855',
    storageBucket: 'nutri-guard-48855.appspot.com',
    iosBundleId: 'com.example.nutriguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT-wzD2r_KOZX_oDSlI3hjzWe2sexS85E',
    appId: '1:304480919302:ios:6ae0e1053b6dfc23e98887',
    messagingSenderId: '304480919302',
    projectId: 'nutri-guard-48855',
    storageBucket: 'nutri-guard-48855.appspot.com',
    iosBundleId: 'com.example.nutriguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjkLevbcna-YzBbhoiXWwkoOtpPUxjTpQ',
    appId: '1:304480919302:web:4d49e653ac3778c0e98887',
    messagingSenderId: '304480919302',
    projectId: 'nutri-guard-48855',
    authDomain: 'nutri-guard-48855.firebaseapp.com',
    storageBucket: 'nutri-guard-48855.appspot.com',
  );
}
